### PR TITLE
Added tfd, RollingWord, ImgOps & FeelingLucky search menu

### PR DESCRIPTION
**Pull request by pine2D**
This is my first time to use Pull Requests. Hope I didn't mess things up.

### CODE REVIEW

**Comment by YungSang** [comment]
おおお、記念すべき初 PR ありがとうございます。

ちょっとだけ修正をお願いしたいのですが、queryString を使っている場合は内部で encodeURIComponent をやるので問題無いのですが、
直接 info.selectionText を使う場合は、 encodeURIComponent(info.selectionText) した方がいいです。

**Comment by YungSang** [comment]
Ooops. Sorry about my comment in Japanese.

Could you revise them a bit?
queryString() does encodeURIComponent() internally, otherwise you have to encode it by yourself using encodeURIComponent.
info.selectionText should be encodeURIComponent(info.selectionText).
Thanks.

**Comment by YungSang** [comment]
@oumu Thank you for the PR, BTW.

**Comment by pine2D** [comment]
Glad I can contribute a little. Do I understand you correctly though? I barely know JavaScript. My patches are just mimics of your menu.photo.search.tineye.tbrl.js & menu.book.meta.search.tbrl.js.

**Comment by YungSang** [comment]
Looks good. I will test them on my side.

**Comment by YungSang** [comment]
Modified URLs and merged.
Thanks.

**Comment by YungSang** [comment]
Sorry for the rejection of "RollingWord Search".
Please host it on your repo.

**Comment by pine2D** [comment]
Got it :wink:

**Pull request merged**
